#This file was originally generated by PyScripter's unitest wizard

import sys, os, re, time
import unittest
import msaa
import comtypes.client

AutoItX = comtypes.client.CreateObject('AutoItX3.Control')

class TestCalc(unittest.TestCase):

    def setUp(self):
        os.startfile('calc.exe')
        time.sleep(3)

    def tearDown(self):
        AutoItX.WinClose('Calculator')

    def testcalc(self):
        w = msaa.window('Calculator')
        b1 = w.find('PushButton', Name='1')
        b1.accDoDefaultAction()
        ba = w.find('PushButton', Name='Add')
        ba.accDoDefaultAction()
        b2 = w.find('PushButton', Name='2')
        b2.accDoDefaultAction()
        be = w.find('PushButton', Name='Equals')
        be.accDoDefaultAction()
        e = w.find('Text', Name=u'Result')
        assert e.accValue() == u'3 '

if __name__ == '__main__':
    unittest.main()

